/**
 * One-off, real-database verification for the Edge/Domain-onboarding
 * layer (DomainOnboardingService + DomainResolutionService), same
 * evidentiary rigor used for the guard-evaluation pipeline, RLS, and the
 * Blueprint Engine earlier in this engagement: proves the full
 * PROPOSED -> checkVerification -> VERIFIED -> activateDomain -> ACTIVE
 * flow against the real growhubs_v2_dev database, then proves
 * DomainResolutionService resolves the newly-created BrandBinding's Host
 * back to the right tenantId.
 *
 * HONEST LIMITATION, stated rather than hidden: this sandbox's outbound
 * DNS resolution is blocked by network policy (confirmed directly: a raw
 * `dns.resolveTxt('google.com')` call from this container timed out).
 * There is no domain this session can actually publish a TXT/CNAME record
 * for either way, so this script cannot prove a REAL DNS lookup finds a
 * real token. Instead it injects a fake DnsResolver (the exact seam
 * dns-resolver.ts's docstring says exists for this reason) that returns
 * canned records — this proves the SERVICE'S OWN LOGIC (state
 * transitions, evidence recording, the eventual BrandBinding creation)
 * against the real database, while leaving "does live DNS I/O actually
 * work in production" honestly unverified here — a real deployment
 * environment with outbound DNS access would need to confirm that
 * separately; NodeDnsResolver itself is a two-line pass-through to
 * Node's own `dns.promises`, not custom logic this codebase invents.
 */
import 'reflect-metadata';
import { AppDataSource } from '../src/data-source';
import { DomainOnboardingService } from '../src/edge/domain-onboarding.service';
import { DomainResolutionService } from '../src/edge/domain-resolution.service';
import { DnsResolver } from '../src/edge/dns-resolver';
import {
  DomainVerification,
  DomainVerificationMethod,
  DomainVerificationStatus,
} from '../src/edge/entities/domain-verification.entity';
import { BrandBinding } from '../src/identity-access/entities/brand-binding.entity';
import { randomUUID } from 'crypto';

class FakeDnsResolver implements DnsResolver {
  constructor(private readonly txtRecordsToReturn: string[][]) {}
  async resolveTxt(_domain: string): Promise<string[][]> {
    return this.txtRecordsToReturn;
  }
  async resolveCname(_domain: string): Promise<string[]> {
    throw new Error('not used in this verification run');
  }
}

async function main() {
  await AppDataSource.initialize();
  const tenantId = randomUUID();
  const requestedDomain = `verify-edge-${randomUUID()}.example.com`;
  let domainVerificationId: string | undefined;
  let bindingId: string | undefined;

  try {
    // --- 1. propose, with a resolver that does NOT yet have the token ----
    const notYetService = new DomainOnboardingService(
      AppDataSource,
      new FakeDnsResolver([['some-unrelated-txt-record']]),
    );
    const proposed = await notYetService.proposeDomain({
      tenantId,
      requestedDomain,
      verificationMethod: DomainVerificationMethod.DNS_TXT_RECORD,
    });
    domainVerificationId = proposed.domainVerificationId;
    console.log('proposed DomainVerification', domainVerificationId, 'status=', proposed.status);
    if (proposed.status !== DomainVerificationStatus.PROPOSED) {
      throw new Error('expected fresh proposal to be PROPOSED');
    }

    const stillPending = await notYetService.checkVerification(domainVerificationId);
    console.log('checkVerification with wrong TXT record -> status=', stillPending.status);
    if (stillPending.status !== DomainVerificationStatus.DNS_CHECK_PENDING) {
      throw new Error('expected checkVerification to stay DNS_CHECK_PENDING when the token is not yet published');
    }

    // --- 2. re-check with a resolver that DOES have the token -------------
    // reload to get the real token generated by proposeDomain
    const reloaded = await AppDataSource.getRepository(DomainVerification).findOneByOrFail({
      domainVerificationId,
    });
    const provenService = new DomainOnboardingService(
      AppDataSource,
      new FakeDnsResolver([[reloaded.verificationToken]]),
    );
    const verified = await provenService.checkVerification(domainVerificationId);
    console.log('checkVerification with correct TXT record -> status=', verified.status);
    if (verified.status !== DomainVerificationStatus.VERIFIED) {
      throw new Error('expected checkVerification to reach VERIFIED once the token matches');
    }
    if (!verified.verifiedAt) throw new Error('expected verifiedAt to be set');

    // --- 3. activate -> creates the BrandBinding row ----------------------
    const binding = await provenService.activateDomain(domainVerificationId);
    bindingId = binding.bindingId;
    console.log('activateDomain -> created BrandBinding', bindingId, 'domain=', binding.domain);
    if (binding.tenantId !== tenantId) throw new Error('BrandBinding.tenantId did not match the proposing tenant');

    const activatedVerification = await AppDataSource.getRepository(DomainVerification).findOneByOrFail({
      domainVerificationId,
    });
    if (activatedVerification.status !== DomainVerificationStatus.ACTIVE) {
      throw new Error('expected DomainVerification to be ACTIVE after activateDomain');
    }
    console.log('confirmed DomainVerification.status === ACTIVE after activation');

    // --- 4. DomainResolutionService resolves the Host back to the tenant -
    const resolutionService = new DomainResolutionService(AppDataSource);
    const resolved = await resolutionService.resolveHost(requestedDomain);
    console.log('resolveHost ->', resolved);
    if (!resolved || resolved.tenantId !== tenantId) {
      throw new Error('expected resolveHost to resolve the activated domain back to the proposing tenant');
    }

    const unresolved = await resolutionService.resolveHost('no-such-domain.example.com');
    if (unresolved !== null) throw new Error('expected an unbound host to resolve to null');
    console.log('confirmed an unbound host resolves to null');

    console.log('ALL CHECKS PASSED');
  } finally {
    if (bindingId) {
      await AppDataSource.getRepository(BrandBinding).delete({ bindingId });
    }
    if (domainVerificationId) {
      await AppDataSource.getRepository(DomainVerification).delete({ domainVerificationId });
    }
    console.log('cleaned up test rows');
    await AppDataSource.destroy();
  }
}

main().catch((err) => {
  console.error('VERIFICATION FAILED', err);
  process.exit(1);
});
